In [2]:
#question 1
import numpy as np
import pandas as pd

In [3]:
arr=np.array([1,7,13,105])

In [4]:
print(arr)

[  1   7  13 105]


In [5]:
print(f'size of array is {arr.size}')

size of array is 4


In [6]:
#question 2
x = np.array([3, 5])
y = np.array([2, 5])
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y)) 

Comparison - greater
[ True False]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [7]:
#question 3
arr1=np.zeros(10)
arr2=np.ones(10)
arr3=arr2*5
arr4=arr2*10


In [8]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [9]:
arr5=arr4*5
arr6=arr4*2

In [10]:
print(arr5)
print(arr6)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [11]:
#question4 
arr7=np.arange(30,70)
print(arr7)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [12]:
#question5
arr8=np.arange(50,95)
print(arr8)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [13]:
#ques6
arr9=np.arange(20,80,2)
arr10=np.arange(21,80,2)
print(arr9)
print(arr10)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [14]:
#ques8
arr11=np.random.randint(10,40,15)
print(arr11)

[24 18 16 32 31 21 24 30 13 35 34 13 16 33 23]


In [15]:
#ques9
arr12=np.random.randint(30,50,10)
print(arr12)

[35 36 35 48 42 43 38 30 33 34]


In [16]:
#ques10
arr13=np.random.randint(50,90,20)
print(arr13)

[71 66 87 82 61 73 64 74 88 61 70 83 71 84 52 62 63 80 66 86]


In [17]:
#ques11
arr14=np.array([10,20,30,40])
arr15=np.array([50,60,70,80])
arr16=arr14+arr15
arr17=arr15-arr14
arr18=arr14*arr15
print(arr16)
print(arr17)
print(arr18)


[ 60  80 100 120]
[40 40 40 40]
[ 500 1200 2100 3200]


In [18]:
#ques12
m = np.arange(10, 22).reshape((3, 4))
print(m)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [19]:
#ques 13
m=np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#ques14
import numpy as np
arr=np.arange(10,22).reshape((3,4))
print(arr)
print(arr.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


In [24]:
#ques15
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [26]:
#ques16
x = np.random.random((3, 3, 3))
print(x)

[[[0.92182546 0.6690654  0.90785119]
  [0.43171056 0.58006195 0.71588945]
  [0.75464963 0.24371485 0.40847687]]

 [[0.6180868  0.11173271 0.94409301]
  [0.57879859 0.83195303 0.29492445]
  [0.83978785 0.25897524 0.19800341]]

 [[0.64870419 0.92214247 0.84766911]
  [0.82360027 0.7029596  0.48574168]
  [0.91635059 0.38515535 0.46829819]]]


In [27]:
#ques17
x = np.random.random((2, 3, 4))
print(x)


[[[0.11828493 0.63546312 0.65358202 0.94638874]
  [0.61347728 0.05079907 0.02732923 0.98635299]
  [0.85123483 0.23103207 0.11408806 0.87085475]]

 [[0.4683455  0.97077596 0.18722532 0.7987144 ]
  [0.28297697 0.80320719 0.21623248 0.46911686]
  [0.78284232 0.88741381 0.2301455  0.48539744]]]


In [29]:
#ques18
l = [12.23, 13.32, 100, 36.32]
a = np.array(l)
print(a)

[ 12.23  13.32 100.    36.32]


In [30]:
#ques19
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [31]:
#ques20
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [33]:
#ques21
x = np.arange(12, 38)
print(x)
x = x[::-1]
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [42]:
#ques22
y = x.astype(float)
print(y)

[20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [43]:
#ques23
lst = [1, 7, 0, 6, 2, 5, 6]
arr = np.array(lst)
print(arr)

[1 7 0 6 2 5 6]


In [37]:
#ques24
x = np.arange(7)
print(np.remainder(x, 4)) 


[0 1 2 3 0 1 2]


In [41]:
#ques25
x=np.arange(20,51)
print(x)
print(np.remainder(x,3))




[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
